# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8fe16ea65e92c111df6e7e0a21386a217c81e95893d77aa73a65b319d1b378ff709786808ae62c0a1599179f1565330318392a1be524806109dd3c649e00fad

test:
  secret_key_base: f98b26e2c5b910a167363c13c81e42daddeaade7fa7edd18c30359c3766ec706f79776ce7a1c4e75d5fd1f1e3d81e1e6405f923f32be0a21b87467eaeb29721c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
